---
# Playbook to include and launch one or more roles

- hosts: localhost
  connection: local
  gather_facts: yes

  

  tasks:
    - name: Debug Facts
      debug:
        var: ansible_distribution
    - name: add hosts from extra-vars
      add_host:
        name: '{{ item }}'
        groups: building
      loop: "{{ hosts_list.split('\n') }}"
      changed_when: false


- hosts: building
  gather_facts: "{{ play_roles_gather_facts | default(false) | bool }}"
  tasks:
    - debug: msg="hosts_list={{ hosts_list | replace('\n',',') }}"
      run_once: true
      when: play_roles_debug | default(false) | bool

    - debug: msg="ansible_play_hosts_all={{ansible_play_hosts_all}}"
      run_once: true
      when: play_roles_debug | default(false) | bool

    - name: Include self role
      include_tasks: tasks/linux.yml

